TTCMS.Web/Areas/TT_Admin/Models/BannerManagement/BannerViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using TTCMS.Web.ViewModels;

namespace TTCMS.Web.Areas.TT_Admin.Models
{
    public class BannerViewModel
    {
        public string Show { get; set; }
        public string Search { get; set; }
        public List<LanguageViewModel> Languages { get; set; }
        public IPagedList<BannerItemViewModel> ModelList { get; set; }
    }
    public class BannerItemViewModel
    {
        public int Id { get; set; }
        public string RedirectUrl { get; set; }
        public string ImageUrl { get; set; }
        public int LanguageId { get; set; }
        public int? Priority { get; set; }
        public bool IsActived { get; set; }
        public DateTime CreatedDate { get; set; }
        public int Type { get; set; }
    }
    public class BannerPageViewModel
    {
        public IEnumerable<SelectListItem> Lang { get; set; }
        public BannerViewModel TableList { get; set; }
    }
     public class BannerCreateViewModel
    {
        public SelectList Lang { get; set; }
        public SelectList ListBannerType { get; set; }
        public BannerItemViewModel Model { get; set; }
    }
}

TTCMS.Web/Areas/TT_Admin/Controllers/BannerManagementController.cs
using AutoMapper;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TTCMS.Areas.TT_Admin.CustomAttributes;
using TTCMS.Areas.TT_Admin.Filters;
using TTCMS.Core.Infrastructure.Alerts;
using TTCMS.Data.Entities;
using TTCMS.Service;
using TTCMS.Service.Common;
using TTCMS.Web.Areas.TT_Admin.Models;
using TTCMS.Web.ViewModels;

namespace TTCMS.Web.Areas.TT_Admin.Controllers
{
    public class BannerManagementController : BaseController
    {
        private readonly IEnumerable<Language> languages;
        private readonly IBannerService BannerService;
        private readonly ILanguage_BannerService language_BannerService;
        private readonly IMediaService mediaService;
        private readonly ILanguageService languageService;
        public BannerManagementController(IBannerService BannerService, ILanguage_BannerService language_BannerService,
            IMediaService mediaService,
            ILanguageService languageService)
        {
            this.BannerService = BannerService;
            this.mediaService = mediaService;
            this.language_BannerService = language_BannerService;
            this.languageService = languageService;
            languages = languageService.GetListForActive();
        }
        // GET: TT_Admin/Banner
        [HttpGet]
        [AuthorizeUser(FunctionID = "BANNER", RoleID = "VIEW")]
        public ActionResult Index(int? page = 1, string show = "", string search = "")
        {
            if (show != "")
            {
                cultureName = show;
            }
            int pageSize = int.Parse(ConfigSettings.ReadSetting("pageSize"));
            int pageNumber = (page ?? 1);
            var banners = BannerService.GetList();
            var bannerItems = new List<BannerItemViewModel>();
            foreach (var item in banners)
            {
                var bannerDetail = language_BannerService.GetByBannerId(item.Id).Select(q => new BannerItemViewModel
                {
                    Id = item.Id,
                    ImageUrl = q.Image?.FullPath,
                    RedirectUrl = q.RedirectURL,
                    Type = (int)item.Type,
                    IsActived = item.IsActived,
                    LanguageId = q.Language.Id,
                    CreatedDate = item.CreatedDate
                });
                bannerItems.AddRange(bannerDetail);
            }
            var table = new BannerViewModel
            {
                Show = show,
                Search = search,
                Languages = Mapper.Map<IEnumerable<Language>, List<LanguageViewModel>>(languages),
                ModelList = new PagedList<BannerItemViewModel>(bannerItems, pageNumber, pageSize),
            };
            table.ModelList.ToPagedList(pageNumber, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_BannerTable", table);
            }

            var model = new BannerPageViewModel
            {
                TableList = table
            };
            return View(model);
        }

        [HttpGet]
        [AuthorizeUser(FunctionID = "BANNER", RoleID = "CREATE")]
        public ActionResult Create()
        {
            var lang = languages;
            var Banner = new BannerItemViewModel
            {
                Id = 0
            };
            var model = new BannerCreateViewModel()
            {
                Model = Banner
            };
            model.Lang = new SelectList(
                lang.OrderByDescending(x => x.CreatedDate),
                "Id",
                "Name",
                model.Model.LanguageId
            );
            var listType = Enum.GetValues(typeof(BannerType))
               .Cast<BannerType>()
               .Select(t => new
               {
                   Id = ((int)t),
                   Name = t.ToString()
               });
            model.ListBannerType = new SelectList(
                listType.OrderByDescending(x => x.Id),
                "Id",
                "Name",
                model.Model.Type
            );
            return View(model);
        }
        [HttpPost]
        [ValidateAntiForgeryToken, Log("{model}")]
        [AuthorizeUser(FunctionID = "BANNER", RoleID = "CREATE")]
        public ActionResult Create(BannerCreateViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid || viewModel.Model.ImageUrl == null || viewModel.Model.ImageUrl == string.Empty)
                {
                    viewModel.Lang = new SelectList(
                        languages.OrderByDescending(x => x.CreatedDate),
                        "Id",
                        "Name",
                        viewModel.Model.LanguageId
                    );
                    var listType = Enum.GetValues(typeof(BannerType))
                        .Cast<BannerType>()
                        .Select(t => new
                        {
                            Id = ((int)t),
                            Name = t.ToString()
                        });
                    viewModel.ListBannerType = new SelectList(
                            listType.OrderByDescending(x => x.Id),
                            "Id",
                            "Name",
                            viewModel.Model.Type
                        );
                    ModelState.AddModelError("", Resources.Resources.WarningData);
                    var listlang = languageService.GetListForActive().ToList();
                    return View(viewModel).WithWarning(Resources.Resources.WarningData);
                }
                var newBanner = new Banner() { IsActived = viewModel.Model.IsActived, Type = (BannerType)viewModel.Model.Type, CreatedDate = DateTime.Now };
                var newLanguageBanner = new Language_Banner()
                {
                    RedirectURL = viewModel.Model.RedirectUrl,
                    LanguageId = viewModel.Model.LanguageId,
                    Priority = viewModel.Model.Priority,
                    CreatedDate = DateTime.Now,
                    BannerId = BannerService.Create(newBanner),
                    Banner = newBanner
                };
                if (!string.IsNullOrEmpty(viewModel.Model.ImageUrl))
                {
                    var mediaViewModel = GetMediaByUrl(viewModel.Model.ImageUrl);
                    var image = mediaService.GetByFullPath(mediaViewModel.FullPath);
                    if (image == null)
                    {
                        image = mediaService.Create(Mapper.Map<MediaViewModel, Media>(mediaViewModel));
                        mediaService.SaveChange();
                    }
                    newLanguageBanner.Image = image;
                }
                language_BannerService.Create(newLanguageBanner);
                language_BannerService.SaveChange();
                return RedirectToAction("Index").WithSuccess(Resources.Resources.SuccessCreate);
            }
            catch (Exception ex)
            {
                HandleException("Message ", ex);
                return RedirectToAction("Index").WithError(Resources.Resources.ErrorCatch);
            }
        }
        [AuthorizeUser(FunctionID = "FAQ", RoleID = "EDIT")]
        public ActionResult Edit(int Id = 0, int LanguageId = 0)
        {
            try
            {
                if (Id == 0 || LanguageId == 0) return RedirectToAction("Index").WithError(Resources.Resources.ErrorNoData);

                var curBanner = BannerService.GetById(Id);
                if (curBanner == null)
                {
                    return RedirectToAction("Index").WithError(Resources.Resources.ErrorNoData);
                }

                var lang = languages;
                var bannerItems = language_BannerService.GetByBannerId(curBanner.Id).Where(b => b.LanguageId == LanguageId).Select(q => new BannerItemViewModel
                {
                    Id = curBanner.Id,
                    ImageUrl = q.Image?.FullPath,
                    RedirectUrl = q.RedirectURL,
                    Priority = q.Priority,
                    CreatedDate = curBanner.CreatedDate,
                    Type = (int)curBanner.Type,
                    LanguageId = q.LanguageId,
                    IsActived = curBanner.IsActived
                });
                var model = new BannerCreateViewModel();
                model.Model = bannerItems.FirstOrDefault();
                model.Lang = new SelectList(
                    lang.Where(l => l.Id == model.Model.LanguageId),
                    "Id",
                    "Name",
                    model.Model.LanguageId
                );
                var listType = Enum.GetValues(typeof(BannerType))
              .Cast<BannerType>()
              .Select(t => new
              {
                  Id = ((int)t),
                  Name = t.ToString()
              });
                model.ListBannerType = new SelectList(
                    listType.OrderByDescending(x => x.Id),
                    "Id",
                    "Name",
                    model.Model.LanguageId
                );
                return View("Create", model);
            }
            catch (Exception ex)
            {
                HandleException("Message", ex);
                return RedirectToAction("Index").WithError(Resources.Resources.ErrorCatch);
            }

        }
        [AuthorizeUser(FunctionID = "FAQ", RoleID = "EDIT"), ValidateInput(false)]
        [HttpPost, ValidateAntiForgeryToken, Log("{model}")]
        public ActionResult Edit(BannerCreateViewModel viewModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ModelState.AddModelError("", Resources.Resources.WarningData);
                    var lang = languageService.GetListForActive().ToList();

TTCMS.Web/Areas/TT_Admin/Views/BannerManagement/Create.cshtml
@model  TTCMS.Web.Areas.TT_Admin.Models.BannerCreateViewModel
@{
    bool isEditPage = Model.Model.Id > 0;
    ViewBag.Title = isEditPage ? TTCMS.Resources.Resources.CreateNewBanner : TTCMS.Resources.Resources.EditBanner;
    string thumbnail = string.IsNullOrEmpty(Model.Model.ImageUrl) ? "/Content/images/add-image.jpg" : Model.Model.ImageUrl;
}

<div class="main-content">
    <div class="main-content-inner">
        <div class="breadcrumbs" id="breadcrumbs">
            <script type="text/javascript">
                try { ace.settings.check('breadcrumbs', 'fixed') } catch (e) { }
            </script>

            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/pk_admin">@TTCMS.Resources.Resources.Home</a>
                </li>
                <li class="active">@TTCMS.Resources.Resources.CreateNewBanner</li>
            </ul><!-- /.breadcrumb -->
        </div>
        <div class="page-content">
            <div class="row">
                @using (Html.BeginForm(isEditPage ? "Edit" : "Create", "BannerManagement", FormMethod.Post, new { @role = "form", @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, string.Empty, new { @class = "text-danger" })
                    @Html.HiddenFor(x => x.Model.Id)
                    <div class="col-xs-8">
                        <!-- PAGE CONTENT BEGINS -->
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">@TTCMS.Resources.Resources.URLText </label>
                            <div class="col-sm-9">
                                @Html.TextBoxFor(x => x.Model.RedirectUrl, new { @class = "col-xs-12 col-sm-12" })
                                @Html.ValidationMessageFor(model => model.Model.RedirectUrl, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">@TTCMS.Resources.Resources.Images <span style="color:red">*</span> </label>
                            <label class="ace-file-input ace-file-multiple">
                                <div class="col-sm-9">
                                    <span class="ace-file-container hide-placeholder selected">
                                        <span data-title="Ảnh đại diện" class="ace-file-name large" id="ThumbnailContainer">
                                            @Html.HiddenFor(x => x.Model.ImageUrl)
                                            <img id="Image" class="middle" style="max-width:250px;max-height:250px;" src="@thumbnail" />
                                            <i class=" ace-icon fa fa-picture-o file-image"></i>
                                        </span>
                                    </span>
                                </div>
                            </label>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">@TTCMS.Resources.Resources.BannerType </label>
                            <div class="col-sm-9">
                                @Html.DropDownListFor(model => model.Model.Type, Model.ListBannerType, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="form-group">
                            <label class="control-label col-xs-12 col-sm-4"> @TTCMS.Resources.Resources.SortText </label>
                            <div class="controls col-xs-12 col-sm-8">
                                <div class="row">
                                    @Html.TextBoxFor(x => x.Model.Priority, new { @class = "col-xs-10 col-sm-4", @placeholder = TTCMS.Resources.Resources.SortText })
                                    <div class="space-6"></div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="col-sm-3 control-label no-padding-right">@TTCMS.Resources.Resources.ActiveText</label>
                            <div class="col-sm-9">
                                <label>
                                    @Html.CheckBoxFor(x => x.Model.IsActived, new { @class = "ace ace-switch ace-switch-4 btn-flat" })
                                    <span class="lbl"></span>
                                </label>
                            </div>
                            <label class="col-sm-3 control-label no-padding-right">@TTCMS.Resources.Resources.LanguageText </label>
                            <div class="col-sm-9">
                                @Html.DropDownListFor(model => model.Model.LanguageId, (SelectList)Model.Lang, new { @class = "form-control" })
                            </div>
                        </div>
                        <div class="space-4"></div>
                        <div class="col-md-5">
                            @Html.ActionLink(@TTCMS.Resources.Resources.BackToList, "Index")
                        </div>
                        <button class="btn btn-info" type="submit">
                            <i class="ace-icon fa fa-check bigger-110"></i>
                            @if (isEditPage)
                            {
                                @TTCMS.Resources.Resources.btnUpdateSubmit
                            }
                            else
                            {
                                @TTCMS.Resources.Resources.btnCreateSubmit
                            }
                        </button>
                    </div>
                }
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div><!-- /.main-content -->
@section Scripts {
    <script src="~/Content/admin/js/fuelux/fuelux.spinner.min.js"></script>
    <script src="~/Content/ckeditor/ckeditor.js"></script>
    <script src="~/Content/ckfinder/ckfinder.js"></script>
    <script src="~/Content/admin/js/bootstrap-colorpicker.min.js"></script>
    <script src="~/Content/admin/js/jquery.maskedinput.min.js"></script>
}
<script>
    window.onload = function () {

        $("#ThumbnailContainer").on("click", function () {
            BrowseServer(handleSelectAction);
        });
        CKEDITOR.replace("ckeditor");
    }
    function handleSelectAction(fileUrl) {
        $('#Model_ImageUrl').val(fileUrl);
        $('#Image').attr("src", fileUrl);
    }
</script>

TTCMS.Web/Areas/TT_Admin/Views/BannerManagement/Index.cshtml
@model TTCMS.Web.Areas.TT_Admin.Models.BannerPageViewModel
@{
    ViewBag.Title = TTCMS.Resources.Resources.Banner;
}

<div class="main-content">
    <div class="main-content-inner">
        <div id="breadcrumbs" class="breadcrumbs">
            <ul class="breadcrumb">
                <li>
                    <i class="ace-icon fa fa-home home-icon"></i>
                    <a href="/pk_admin">@TTCMS.Resources.Resources.Home</a>
                </li>
                <li class="active">Banner
                <li>
            </ul><!-- /.breadcrumb -->
        </div>
        <div class="page-content">
            <div class="page-header">
                <div class="toolbar tt-table-header">
                    <div style="float:left">
                        <a href="@Url.Action("Create")" class="btn btn-primary">
                            <i class="menu-icon fa fa-plus"></i>
                            <span class="hidden-320">@TTCMS.Resources.Resources.Create</span>
                        </a>
                    </div>
                    <div style="float:right">
                        @TTCMS.Resources.Resources.ShowbyText
                        @*@Html.DropDownList("ShowId", Model.Lang, "Mặt định", new { @onchange = "LoadFunction('/TT_Admin/NewsCateManagement/Index');" })*@
                        @TTCMS.Resources.Resources.SearchText
                        <span class="input-icon">
                            <input type="text" autocomplete="off" id="Search" onkeyup="SearchAjax('/TT_Admin/NewsCateManagement/Index');" class="nav-search-input" placeholder="@TTCMS.Resources.Resources.EnterKeywordText">
                            <i class="ace-icon fa fa-search nav-search-icon"></i>
                        </span>
                    </div>
                </div>
            </div><!-- /.page-header -->
            <div class="row">
                <div class="col-xs-12">
                    <!-- PAGE CONTENT BEGINS -->
                    <div class="row">
                        <div class="col-xs-12">
                            <div id="TableContainer">
                                @if (Model.TableList != null)
                                {
                                    @Html.Partial("_BannerTable", Model.TableList)
                                }
                            </div>
                        </div><!-- /.span -->
                    </div><!-- /.row -->
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.page-content -->
    </div>
</div>
@section Scripts {
    <script>
        var active_class = 'active';
        $('#simple-table > thead > tr > th input[type=checkbox]').eq(0).on('click', function () {
            var th_checked = this.checked;//checkbox inside "TH" table header

            $(this).closest('table').find('tbody > tr').each(function () {
                var row = this;
                if (th_checked) $(row).addClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', true);
                else $(row).removeClass(active_class).find('input[type=checkbox]').eq(0).prop('checked', false);
            });
        });

        //select/deselect a row when the checkbox is checked/unchecked
        $('#simple-table').on('click', 'td input[type=checkbox]', function () {
            var $row = $(this).closest('tr');
            if (this.checked) $row.addClass(active_class);
            else $row.removeClass(active_class);
        });
    </script>
}

TTCMS.Web/Areas/TT_Admin/Views/BannerManagement/_BannerTable.cshtml
@model TTCMS.Web.Areas.TT_Admin.Models.BannerViewModel
@using TTCMS.Data.Entities
@using PagedList.Mvc;

<style>
    .btn-group {
        display: flex;
    }

        .btn-group > * {
            margin-right: 8px;
        }

    .dropdown {
        display: inline-block;
    }

        .dropdown .btn-xs {
            border-width: 1px;
        }
</style>

@if (Model.ModelList.Any())
{
    <input id="Page" type="hidden" value="@Model.ModelList.PageNumber" />
    <table class="table table-striped table-bordered table-hover" id="simple-table">
        <thead>
            <tr>
                <th class="center">
                    <label class="pos-rel">
                        <input type="checkbox" class="ace">
                        <span class="lbl"></span>
                    </label>
                </th>
                <th>@TTCMS.Resources.Resources.LinkTextURL</th>
                <th>@TTCMS.Resources.Resources.Images</th>
                <th>@TTCMS.Resources.Resources.Possition</th>
                <th>@TTCMS.Resources.Resources.LanguageText</th>
                <th>
                    <i class="ace-icon fa fa-clock-o bigger-110 hidden-480"></i>
                    @TTCMS.Resources.Resources.Created
                </th>
                <th class="hidden-480">@TTCMS.Resources.Resources.Status</th>
                <th>@TTCMS.Resources.Resources.Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ModelList)
            {
            <tr id="item_@item.Id">
                <td class="center">
                    <label class="pos-rel">
                        <input type="checkbox" class="ace" value="@item.Id">
                        <span class="lbl"></span>
                    </label>
                </td>
                <td>@item.RedirectUrl</td>
                <td>@item.ImageUrl</td>
                <td>@(((BannerType)item.Type).ToString())</td>
                <td>@Model.Languages.Where(l => l.Id == item.LanguageId).FirstOrDefault().Name</td>
                <td>@string.Format("{0:dd/MM/yyyy}", item.CreatedDate)</td>
                <td class="hidden-480">
                    @if (item.IsActived == true)
                    {
                        <span class="label label-sm label-success arrowed arrowed-right">
                            <i class="fa fa-unlock"></i> Active
                        </span>
                    }
                    else
                    {
                        <span class="label label-sm label-danger arrowed arrowed-right">
                            <i class="fa fa-unlock-alt"></i> NotActive
                        </span>
                    }
                </td>
                <td>
                    <div class="hidden-sm hidden-xs btn-group">

                        <a href="@Url.Action("Edit", "BannerManagement", new { Id = item.Id , LanguageId = item.LanguageId })" class="btn btn-primary">
                            <span class="hidden-320">@TTCMS.Resources.Resources.EditText</span>
                        </a>
                        @Ajax.ActionLink(
                            TTCMS.Resources.Resources.DeleteText,
                            "Delete",
                            new { Id = item.Id },
                            new AjaxOptions()
                            {
                                HttpMethod = "Delete",
                                Confirm = TTCMS.Resources.Resources.ConfirmText,
                                UpdateTargetId = @item.Id.ToString(),
                                OnSuccess = "onSuccess"
                            },
                            new
                            {
                                @class = "btn btn-xs btn-danger DeleteDialog",
                                @title = TTCMS.Resources.Resources.DeletePost
                            }
                        )

                    </div>
                    <div class="hidden-md hidden-lg">
                        <div class="inline pos-rel">
                            <button data-position="auto" data-toggle="dropdown" class="btn btn-minier btn-primary dropdown-toggle">
                                <i class="ace-icon fa fa-cog icon-only bigger-110"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-only-icon dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                <li>
                                    <a title="@TTCMS.Resources.Resources.EditPost" class="btn btn-xs btn-info" href="@Url.Action("Edit", new {Id = item.Id })">
                                        @TTCMS.Resources.Resources.EditText
                                    </a>
                                </li>
                                <li>
                                    @Ajax.ActionLink(TTCMS.Resources.Resources.DeleteText, "Delete", new { Id = item.Id },
                                        new AjaxOptions()
                                        {
                                            HttpMethod = "Delete",
                                            Confirm = TTCMS.Resources.Resources.ConfirmText,
                                            UpdateTargetId = @item.Id.ToString(),
                                            OnSuccess = "onSuccess"
                                        }, new { @class = "btn btn-xs btn-danger DeleteDialog", @title = TTCMS.Resources.Resources.DeletePost })
                                </li>
                            </ul>
                        </div>
                    </div>
                </td>
            </tr>
            }
        </tbody>
    </table>
    <div class="row">
        <div class="col-xs-6"><div class="dataTables_info" id="dynamic-table_info" role="status" aria-live="polite">@TTCMS.Resources.Resources.Page @(Model.ModelList.PageCount < Model.ModelList.PageNumber ? 0 : Model.ModelList.PageNumber) @TTCMS.Resources.Resources.Of @Model.ModelList.PageCount</div></div>
        <div class="col-xs-6 no-padding">
            <div class="dataTables_paginate paging_simple_numbers" id="ajax_paging">
                @Html.PagedListPager(
                    Model.ModelList,
                    page => Url.Action("Index",
                    new { page, show = Model.Show, search = Model.Search }),
                    PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new AjaxOptions { UpdateTargetId = "TableContainer" })
                )
            </div>
        </div>
    </div>
}
else
{
    @Html.Partial("_AlertInfo", @TTCMS.Resources.Resources.ErrorNoData);
}